apiVersion: v1
kind: Service
metadata:
  name: idasen-restapi-desk
  namespace: default
  labels:
    app: idasen-restapi-desk
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:    
    app: idasen-restapi-desk
  type: ClusterIP